# Generated by Django 5.2.16 on 2026-07-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_alter_leadcapture_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcapture',
            name='followup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadcapture',
            name='followup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
