# Generated by Django 5.2.15 on 2026-08-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0013_leadcapture_followup_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadcapture",
            name="phone_no",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
