# Generated by Django 5.2.15 on 2026-08-20 07:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0014_alter_leadcapture_phone_no"),
        ("staff", "0021_staff_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadCaptureTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_count",
                    models.PositiveIntegerField(
                        help_text="Number of leads to be captured"
                    ),
                ),
                ("achieved_count", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Marketing Lead / Admin / Manager who assigned this target",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_lead_capture_targets",
                        to="staff.staff",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        help_text="Marketing team member this target is assigned to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_capture_targets",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "db_table": "lead_capture_targets",
                "ordering": ["-created_at"],
            },
        ),
    ]
