# Generated by Django 5.2.16 on 2026-07-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_alter_staff_monthly_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrole',
            name='role_name',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Trainer', 'Trainer'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('HR', 'HR'), ('Sales Exec', 'Sales Exec'), ('Sales Exec Lead', 'Sales Exec Lead'), ('Digital Marketing', 'Digital Marketing'), ('Content Creator', 'Content Creator'), ('Marketing Lead', 'Marketing Lead')], max_length=100, unique=True),
        ),
    ]
