# Generated by Django 5.2.16 on 2026-07-27 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_alter_staffrole_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026)),
                ('month', models.PositiveSmallIntegerField(default=7)),
                ('week', models.PositiveSmallIntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4'), (5, 'Week 5')])),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_performances', to='staff.staff')),
            ],
            options={
                'ordering': ['year', 'month', 'week'],
                'unique_together': {('staff', 'year', 'month', 'week')},
            },
        ),
    ]
