# Generated by Django 5.2.15 on 2026-08-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0017_staff_address_staff_blood_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklyperformance",
            name="month",
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
