# Generated by Django 5.2.15 on 2026-08-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0018_alter_weeklyperformance_month"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="employment_type",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="marital_status",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="personal_email",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="work_location",
        ),
    ]
