# Generated by Django 5.2.15 on 2026-08-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0019_remove_staff_employment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="reporting_manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"status": "active"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_members",
                to="staff.staff",
            ),
        ),
    ]
