# Generated by Django 5.2.15 on 2026-09-22 12:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='documents',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='staff/documents/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='staff/photos/'),
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='document',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='staff/documents/'),
        ),
        migrations.AlterField(
            model_name='weeklyperformance',
            name='month',
            field=models.PositiveSmallIntegerField(default=9),
        ),
    ]
