# Generated by Django 5.2.15 on 2026-08-19 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_attendance",
            "0004_alter_attendance_trainer_alter_batch_trainer_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Trainer",
        ),
    ]
