# Generated by Django 5.2.15 on 2026-08-20 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admissions",
            "0006_remove_student_certificate_remove_student_id_proof_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="guardian_phone_no",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with +91 and contain exactly 10 digits.",
                        regex="^\\+91[6-9]\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_no",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with +91 and contain exactly 10 digits.",
                        regex="^\\+91[6-9]\\d{9}$",
                    )
                ],
            ),
        ),
    ]
